name: frog

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Place chrome...
      run: ./setup.ps1
    - name: Copy scripts
      run: copy cron2.py C:\Users\runneradmin\cron2.py
    - name: Run scripts
      run: python C:\Users\runneradmin\cron2.py
